spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://localhost:5432/neoflex-credit-bank-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        delivery.timeout.ms: 5000
        request.timeout.ms: 3000
        max.block.ms: 5000
        retries: 3
      acks: all
server:
  port: 8082
calculator:
  base-url: http://localhost:8081/calculator